//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirPortWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilot
    {
        public string PilotId { get; set; }
        public string PilotName { get; set; }
        public string LicenceNo { get; set; }
        public string SSNo { get; set; }
        public System.DateTime Dob { get; set; }
        public string Gender { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string AddressId { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
